import os
import sys
from openai import OpenAI

API_KEY = os.getenv("OPENAI_API_KEY")

if not API_KEY:
    print("Error: OPENAI_API_KEY not found in environment variables.")
    sys.exit(1)

client = OpenAI(api_key=API_KEY)

AVA_SYSTEM_PROMPT = """
You are **Ava**, the UX/UI Designer.

YOUR MISSION
- Design the visual and interaction system for the project.
- Produce a detailed, implementation-ready design spec.
(Full prompt preserved here)
"""


class AvaAgent:
    def __init__(self):
        self.messages = [
            {"role": "system", "content": AVA_SYSTEM_PROMPT}
        ]

    def generate_design(self, project_spec, work_packages):
        user_content = (
            f"CONTEXT (PROJECT SPEC):\n{project_spec}\n\n"
            f"TASK (WORK PACKAGES):\n{work_packages}\n\n"
            "Please generate the detailed DesignSpec based on the above."
        )

        self.messages.append({"role": "user", "content": user_content})

        try:
            print("\n[Ava]: Reviewing architecture and visualizing the interface...")
            completion = client.chat.completions.create(
                model="gpt-4o",
                messages=self.messages,
                temperature=0.4
            )
            response = completion.choices[0].message.content
            self.messages.append({"role": "assistant", "content": response})
            return response
        except Exception as e:
            return f"Error communicating with Ava: {e}"


def get_multiline_input(instruction):
    print(f"\n{instruction}")
    print("(Type 'DONE' on a new line when finished)")
    lines = []
    while True:
        line = input()
        if line.strip() == "DONE":
            break
        lines.append(line)
    return "\n".join(lines)


def main():
    print("\n--- INITIALIZING AVA: THE UX/UI DESIGNER ---\n")
    agent = AvaAgent()

    print("Ava: I need the Project Spec generated by Riley.")
    choice = input("     Load from 'ProjectSpec.md'? (y/n): ").strip().lower()

    project_spec = ""
    if choice == "y" and os.path.exists("ProjectSpec.md"):
        with open("ProjectSpec.md", "r") as f:
            project_spec = f.read()
        print(f"     [System]: Loaded {len(project_spec)} chars from file.")
    else:
        project_spec = get_multiline_input("Ava: Paste Project Spec below:")

    if not project_spec.strip():
        print("Error: No spec. Exiting.")
        return

    print("\nAva: Any specific design packages?")
    work_packages = input("Packages: ")
    if not work_packages.strip():
        work_packages = "ALL UI/UX REQUIREMENTS identified in the ProjectSpec."

    response = agent.generate_design(project_spec, work_packages)

    print("\n" + "="*40)
    print(" DESIGN SPECIFICATION & ASSET LIST ")
    print("="*40 + "\n")
    print(response)

    save = input("\nSave to 'DesignSpec.md'? (y/n): ").lower()
    if save == "y":
        with open("DesignSpec.md", "w") as f:
            f.write(response)
        print("[System]: Saved to DesignSpec.md")


if __name__ == "__main__":
    main()
