import { AgentDefinition, AgentId } from "./types";

export const agentRegistry: AgentDefinition[] = [
  {
    id: "mia",
    displayName: "Mia – Orchestrator",
    role: "Pipeline conductor",
    description: "Sets strategy, coordinates hand-offs, and checks readiness.",
    stage: "orchestration",
    dependencies: [],
    promptFilePath: "/agents/mia.md",
  },
  {
    id: "jordan",
    displayName: "Jordan – Discovery Lead",
    role: "Requirement analyst",
    description: "Synthesizes goals, constraints, and user personas.",
    stage: "discovery",
    dependencies: ["mia"],
    promptFilePath: "/agents/jordan.md",
  },
  {
    id: "riley",
    displayName: "Riley – Planner",
    role: "Project spec architect",
    description: "Produces structured specs, APIs, and acceptance criteria.",
    stage: "planning",
    dependencies: ["jordan"],
    promptFilePath: "/agents/riley.md",
  },
  {
    id: "ava",
    displayName: "Ava – Product Designer",
    role: "UX/UI design",
    description: "Creates layout strategy, design language, and flows.",
    stage: "design",
    dependencies: ["riley"],
    promptFilePath: "/agents/ava.md",
  },
  {
    id: "liam",
    displayName: "Liam – Frontend Engineer",
    role: "Implements UI",
    description: "Builds the frontend experience and routes.",
    stage: "frontend",
    dependencies: ["ava"],
    promptFilePath: "/agents/liam.md",
  },
  {
    id: "noah",
    displayName: "Noah – Backend Engineer",
    role: "API and services",
    description: "Builds APIs, services, and auth flows.",
    stage: "backend",
    dependencies: ["riley"],
    promptFilePath: "/agents/noah.md",
  },
  {
    id: "sophia",
    displayName: "Sophia – Data Architect",
    role: "Database design",
    description: "Designs schema, migrations, and storage strategy.",
    stage: "database",
    dependencies: ["riley"],
    promptFilePath: "/agents/sophia.md",
  },
  {
    id: "kai",
    displayName: "Kai – Web3 Engineer",
    role: "Smart contracts",
    description: "Designs and implements dApp/contract layer.",
    stage: "web3",
    dependencies: ["noah"],
    promptFilePath: "/agents/kai.md",
  },
  {
    id: "iris",
    displayName: "Iris – Asset Curator",
    role: "Assets and branding",
    description: "Creates and organizes media assets.",
    stage: "assets",
    dependencies: ["ava"],
    promptFilePath: "/agents/iris.md",
  },
  {
    id: "nova",
    displayName: "Nova – Infra & Performance",
    role: "Infrastructure",
    description: "Optimizes deployment, observability, and performance.",
    stage: "integration",
    dependencies: ["noah", "sophia"],
    promptFilePath: "/agents/nova.md",
  },
  {
    id: "ethan",
    displayName: "Ethan – QA",
    role: "Tests and checks",
    description: "Adds automated tests and quality gates.",
    stage: "qa",
    dependencies: ["liam", "noah"],
    promptFilePath: "/agents/ethan.md",
  },
  {
    id: "grace",
    displayName: "Grace – Auditor",
    role: "Risk and compliance",
    description: "Performs audits and security reviews.",
    stage: "audit",
    dependencies: ["ethan"],
    promptFilePath: "/agents/grace.md",
  },
  {
    id: "owen",
    displayName: "Owen – Integrator",
    role: "Packaging and integration",
    description: "Combines outputs, wiring, and deployment package.",
    stage: "integration",
    dependencies: ["liam", "noah", "sophia", "kai", "nova", "grace"],
    promptFilePath: "/agents/owen.md",
  },
  {
    id: "chloe",
    displayName: "Chloe – Documentation",
    role: "Docs and handoff",
    description: "Summarizes deliverables and creates onboarding docs.",
    stage: "docs",
    dependencies: ["owen"],
    promptFilePath: "/agents/chloe.md",
  },
];

export const agentMap: Record<AgentId, AgentDefinition> = agentRegistry.reduce(
  (acc, agent) => {
    acc[agent.id] = agent;
    return acc;
  },
  {} as Record<AgentId, AgentDefinition>,
);
