import os
import sys
import subprocess
import time
import shutil

# ==========================================
# CONFIGURATION
# ==========================================
API_KEY = os.getenv("OPENAI_API_KEY")

# Mapping Agent Roles to their Scripts
AGENTS = {
    "JORDAN": "jordan_agent.py",
    "RILEY": "riley_agent.py",
    "AVA": "ava_agent.py",
    "LIAM": "liam_agent.py",
    "NOAH": "noah_agent.py",
    "SOPHIA": "sophia_agent.py",
    "KAI": "kai_agent.py",
    "IRIS": "iris_agent.py",
    "NOVA": "nova_agent.py",
    "ETHAN": "ethan_agent.py",
    "GRACE": "grace_agent.py",
    "OWEN": "owen_agent.py",
    "CHLOE": "chloe_agent.py"
}

# ==========================================
# HELPER FUNCTIONS
# ==========================================
def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def print_header(title):
    print("\n" + "="*50)
    print(f" {title.center(48)} ")
    print("="*50 + "\n")

def check_script(agent_name):
    script = AGENTS.get(agent_name)
    if not os.path.exists(script):
        print(f"❌ [Mia]: Critical Error. Agent script '{script}' not found.")
        print("   Please ensure all agent python files are in this directory.")
        return False
    return True

def run_agent(agent_name, task_desc):
    """
    Calls the agent script as a subprocess. 
    This allows the agent to take over the terminal IO for interaction.
    """
    if not check_script(agent_name):
        return False

    script = AGENTS[agent_name]
    print(f"📞 [Mia]: Calling {agent_name} ({task_desc})...")
    time.sleep(1)  # Dramatic pause for realism

    try:
        # Request approval before launching a subprocess (best-effort)
        try:
            from agents.utils.api_clients import request_tool_approval, poll_tool_approval
            next_base = os.environ.get("NEXT_BASE_URL", "http://localhost:3000")
            req_id = request_tool_approval(next_base, "Mia", "subprocess", "run_agent", {"agent": agent_name, "script": script}, timeout=5)
            approved = False
            if req_id:
                res = poll_tool_approval(next_base, req_id, poll_interval=1.0, timeout=20)
                if res and res.get("approved") is True:
                    approved = True
            else:
                approved = True
        except Exception:
            approved = True

        if not approved:
            print(f"❌ [Mia]: User did not approve running {agent_name} ({script}). Skipping.")
            return False

        # We use sys.executable to ensure we use the same python env
        subprocess.run([sys.executable, script], check=False)
        print(f"✅ [Mia]: {agent_name} has finished their task.")
        return True
    except Exception as e:
        print(f"❌ [Mia]: Failed to run {agent_name}. Error: {e}")
        return False

def verify_artifact(filename, description):
    """
    Checks if a file exists. If not, warns the user.
    """
    if os.path.exists(filename):
        print(f"   -> Found Artifact: {filename}")
        return True
    else:
        print(f"   -> ⚠️ Warning: {filename} was not generated by the previous agent.")
        return False

# ==========================================
# MIA'S LOGIC
# ==========================================
def main():
    # 1. INIT
    if not API_KEY:
        print("❌ Error: OPENAI_API_KEY not set.")
        sys.exit(1)

    clear_screen()
    print_header("MIA: THE ORCHESTRATOR")
    print("Mia: Hello! I am the UI Router for this multi-agent system.")
    print("     I will coordinate the team to build your software.")

    # 2. SELECT PROJECT TYPE
    print("Mia: What are we building today?")
    options = ["Website", "Web App", "Mobile App", "Database System", "Web3 dApp"]
    for i, opt in enumerate(options, 1):
        print(f"  {i}. {opt}")

    choice = input("\nSelect (1-5): ").strip()
    project_type = options[int(choice)-1] if choice.isdigit() and 0 < int(choice) <= 5 else "Custom Project"

    print(f"\n[Mia]: Understood. Initializing workflow for a **{project_type}**.")

    # 3. PHASE 1: DISCOVERY (Jordan)
    print_header("PHASE 1: DISCOVERY")
    run_agent("JORDAN", "Requirements Gathering")
    if not verify_artifact("DiscoveryReport.md", "Discovery Report"):
        print("[Mia]: Cannot proceed without requirements. Exiting.")
        sys.exit(1)

    # 4. PHASE 2: PLANNING (Riley)
    print_header("PHASE 2: PLANNING")
    run_agent("RILEY", "Architecture & Spec")
    if not verify_artifact("ProjectSpec.md", "Project Specification"):
        print("[Mia]: Architecture planning failed. Exiting.")
        sys.exit(1)

    # 5. PHASE 3: SPECIALIST BUILD LOOP
    print_header("PHASE 3: CONSTRUCTION")
    print("[Mia]: I am dispatching the work packages to the specialists.")

    # 5a. Design
    run_agent("AVA", "UI/UX Design")
    verify_artifact("DesignSpec.md", "Design System")

    # 5b. Database (Sophia)
    run_agent("SOPHIA", "Database Schema")

    # 5c. Backend (Noah)
    run_agent("NOAH", "API & Logic")

    # 5d. Web3 (Kai) - Optional
    if "Web3" in project_type:
        run_agent("KAI", "Smart Contracts")

    # 5e. Frontend (Liam)
    run_agent("LIAM", "Frontend Components")

    # 5f. Assets (Iris & Nova)
    print("\n[Mia]: Do you need AI-generated assets? (Images/Video)")
    asset_choice = input("       (y/n): ").strip().lower()
    if asset_choice == 'y':
        run_agent("IRIS", "Image Generation")
        run_agent("NOVA", "Video/Motion")

    # 6. PHASE 4: QUALITY ASSURANCE
    print_header("PHASE 4: QUALITY CONTROL")

    # 6a. Static Analysis (Grace)
    run_agent("GRACE", "Code Audit")
    if os.path.exists("AuditReport.md"):
        print("[Mia]: Audit issues found. Review 'AuditReport.md' before proceeding.")
        input("Press Enter to continue to Testing...")

    # 6b. Testing (Ethan)
    run_agent("ETHAN", "Test Suites")

    # 7. PHASE 5: INTEGRATION & PACKAGING
    print_header("PHASE 5: INTEGRATION")
    run_agent("OWEN", "Build & Package")

    # Check for ZIP
    zip_files = [f for f in os.listdir('.') if f.endswith('.zip') and 'release' in f]
    if zip_files:
        latest_zip = max(zip_files, key=os.path.getctime)
        print(f"✅ [Mia]: Build successful. Archive ready: {latest_zip}")
    else:
        print("⚠️ [Mia]: Integration finished, but no ZIP file was detected.")

    # 8. PHASE 6: DOCUMENTATION & HANDOFF
    print_header("PHASE 6: HANDOFF")
    run_agent("CHLOE", "Documentation")

    print_header("MISSION COMPLETE")
    print("Mia: The team has finished. Here is your delivery:")

    print("\n📁 PROJECT FILES:")
    if os.path.exists("release_build"):
        print("   - /release_build (Source Code)")
    if zip_files:
        print(f"   - {latest_zip} (Deployable Archive)")

    print("\n📄 DOCUMENTATION:")
    print("   - README.md")
    print("   - ProjectSpec.md")

    print("\n[Mia]: Thank you for using the Agency. Goodbye!")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n[Mia]: Shutdown requested. Have a nice day.")
